cookies: 
  - "JSESSIONID=1234567890ABCDEF"
  - "JSESSIONID=9876543210FEDCBA"


headers:
  User-Agent: "Mozilla/5.0 (Linux; Android 14; XXXXX Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/130.0.6723.107 Mobile Safari/537.36 (schild:5a27955fa63048c70efb8eff4e99fc35) (device:XXXX) Language/zh_CN com.chaoxing.mobile/ChaoXingStudy_3_6.4.4_android_phone_10830_262 (@Kalimdor)_1827918279"
